# Generated by Django 2.1.4 on 2019-01-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='queston',
            new_name='question',
        ),
    ]
